version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: pet_archive_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pet_archive
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpassword
      TZ: Asia/Seoul
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: